# LaTeX Makefile

latexmain = skript-diffgeom
MAKEINDEXSTYLE = index.ist

all: $(latexmain).pdf

$(latexmain).pdf: $(latexmain).tex vc.tex chapter/*.tex
	pdflatex $(latexmain).tex
	bibtex $(latexmain).aux
	makeindex -s $(MAKEINDEXSTYLE) "$(latexmain)"
	pdflatex $(latexmain).tex



vc.tex: .git/logs/HEAD
	echo "%%% This file is generated by Makefile." > vc.tex
	echo "%%% Do not edit this file!\n%%%" >> vc.tex
	git log -1 --format="format:\
		\\gdef\\GITAbrHash{%h}\
		\\gdef\\GITAuthorDate{%ad}\
		\\gdef\\GITAuthorName{%an}" >> vc.tex
	echo "\gdef\GITVersionTag{" >> vc.tex
	git describe --abbrev=0 --tags >> vc.tex
	echo "}" >> vc.tex
